(cl:in-package gps_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          POS_STATUS-VAL
          POS_STATUS
          UTC-VAL
          UTC
          LAT-VAL
          LAT
          LAT_DIR-VAL
          LAT_DIR
          LON-VAL
          LON
          LON_DIR-VAL
          LON_DIR
          QUAL-VAL
          QUAL
          SATS-VAL
          SATS
          HDOP-VAL
          HDOP
          ALT-VAL
          ALT
          A_UNITS-VAL
          A_UNITS
          UNDULATION-VAL
          UNDULATION
          U_UNITS-VAL
          U_UNITS
          AGE-VAL
          AGE
          STN_ID-VAL
          STN_ID
))