// Generated by gencpp from file gps_msg/Gps_GGA.msg
// DO NOT EDIT!


#ifndef GPS_MSG_MESSAGE_GPS_GGA_H
#define GPS_MSG_MESSAGE_GPS_GGA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gps_msg
{
template <class ContainerAllocator>
struct Gps_GGA_
{
  typedef Gps_GGA_<ContainerAllocator> Type;

  Gps_GGA_()
    : header()
    , pos_status()
    , utc(0.0)
    , lat(0.0)
    , lat_dir()
    , lon(0.0)
    , lon_dir()
    , qual(0)
    , sats(0)
    , hdop(0.0)
    , alt(0.0)
    , a_units()
    , undulation(0.0)
    , u_units()
    , age()
    , stn_ID(0)  {
    }
  Gps_GGA_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos_status(_alloc)
    , utc(0.0)
    , lat(0.0)
    , lat_dir(_alloc)
    , lon(0.0)
    , lon_dir(_alloc)
    , qual(0)
    , sats(0)
    , hdop(0.0)
    , alt(0.0)
    , a_units(_alloc)
    , undulation(0.0)
    , u_units(_alloc)
    , age(_alloc)
    , stn_ID(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pos_status_type;
  _pos_status_type pos_status;

   typedef double _utc_type;
  _utc_type utc;

   typedef double _lat_type;
  _lat_type lat;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lat_dir_type;
  _lat_dir_type lat_dir;

   typedef double _lon_type;
  _lon_type lon;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lon_dir_type;
  _lon_dir_type lon_dir;

   typedef uint8_t _qual_type;
  _qual_type qual;

   typedef uint8_t _sats_type;
  _sats_type sats;

   typedef float _hdop_type;
  _hdop_type hdop;

   typedef double _alt_type;
  _alt_type alt;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _a_units_type;
  _a_units_type a_units;

   typedef float _undulation_type;
  _undulation_type undulation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _u_units_type;
  _u_units_type u_units;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _age_type;
  _age_type age;

   typedef int64_t _stn_ID_type;
  _stn_ID_type stn_ID;





  typedef boost::shared_ptr< ::gps_msg::Gps_GGA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_msg::Gps_GGA_<ContainerAllocator> const> ConstPtr;

}; // struct Gps_GGA_

typedef ::gps_msg::Gps_GGA_<std::allocator<void> > Gps_GGA;

typedef boost::shared_ptr< ::gps_msg::Gps_GGA > Gps_GGAPtr;
typedef boost::shared_ptr< ::gps_msg::Gps_GGA const> Gps_GGAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_msg::Gps_GGA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_msg::Gps_GGA_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gps_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gps_msg': ['/home/dyc/Documents/catkin_ws/src/gps_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gps_msg::Gps_GGA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_msg::Gps_GGA_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_msg::Gps_GGA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_msg::Gps_GGA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_msg::Gps_GGA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_msg::Gps_GGA_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_msg::Gps_GGA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e3d6806e31e5486a0581e347bc3ff13";
  }

  static const char* value(const ::gps_msg::Gps_GGA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e3d6806e31e5486ULL;
  static const uint64_t static_value2 = 0xa0581e347bc3ff13ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_msg::Gps_GGA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_msg/Gps_GGA";
  }

  static const char* value(const ::gps_msg::Gps_GGA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_msg::Gps_GGA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
string pos_status   # 位置状态 A=有效，V=无效  我自己添加\n\
# GAGGA 数据包msg\n\
float64 utc         # hhmmss.ss\n\
float64 lat         # 经度\n\
string  lat_dir\n\
float64 lon         # 纬度\n\
string  lon_dir\n\
uint8   qual        # GPS质量指示符  0=定位不可用  1=单点定位  2=伪距差分或SBAS定位，4=RTK固定解，5=RTK浮点解，6=惯导定位\n\
uint8   sats        # 使用中的卫星数，可能与所见数不一致\n\
float32 hdop        # 水平精度因子\n\
float64 alt         # 天线海拔高度，低于大地水准面为负值\n\
string  a_units     # 天线高度单位\n\
float32 undulation  # 大地水准面差距-大地水准面和WGS84椭球面之间的距离，大地水准面高于椭球面为正值，否则为负\n\
string  u_units     # 大地水准面差距单位\n\
string  age         # 差分数据龄期，秒为单位（没有差分数据时为空）\n\
int64   stn_ID      # 差分基站ID，0000-4096 （没有差分数据时为空）\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gps_msg::Gps_GGA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_msg::Gps_GGA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos_status);
      stream.next(m.utc);
      stream.next(m.lat);
      stream.next(m.lat_dir);
      stream.next(m.lon);
      stream.next(m.lon_dir);
      stream.next(m.qual);
      stream.next(m.sats);
      stream.next(m.hdop);
      stream.next(m.alt);
      stream.next(m.a_units);
      stream.next(m.undulation);
      stream.next(m.u_units);
      stream.next(m.age);
      stream.next(m.stn_ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gps_GGA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_msg::Gps_GGA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_msg::Gps_GGA_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pos_status);
    s << indent << "utc: ";
    Printer<double>::stream(s, indent + "  ", v.utc);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lat_dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lat_dir);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "lon_dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lon_dir);
    s << indent << "qual: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.qual);
    s << indent << "sats: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sats);
    s << indent << "hdop: ";
    Printer<float>::stream(s, indent + "  ", v.hdop);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
    s << indent << "a_units: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.a_units);
    s << indent << "undulation: ";
    Printer<float>::stream(s, indent + "  ", v.undulation);
    s << indent << "u_units: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.u_units);
    s << indent << "age: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.age);
    s << indent << "stn_ID: ";
    Printer<int64_t>::stream(s, indent + "  ", v.stn_ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_MSG_MESSAGE_GPS_GGA_H
